const data = {
  products: [
    {
      _id: '1',
      name: 'Women Jeans',
      slug: 'women-stock-jeans',
      category: 'Shirts',
      image: '/images/women-jeans-54.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '2',
      name: 'Men T shirts',
      slug: 'men-t-shirt',
      category: 'Shirts',
      image: '/images/t-shirt24.jpg',
      price: 150,
      countInStock: 0,
      brand: 'Ralph Lauren',
      rating: 3.5,
      numReviews: 15,
      description: 'high quality shirt',
    },
    {
      _id: '3',
      name: 'Long Polo Shirts',
      slug: 'long-polo--shirts',
      category: 'Shirts',
      image: '/images/longpolo-34.jpg',
      price: 200,
      countInStock: 10,
      brand: 'Polo Ralf Lauren',
      rating: 5,
      numReviews: 5,
      description: 'high quality classic wear',
    },
    {
      _id: '4',
      name: 'Men Blue Jeans',
      slug: 'men-blue-jeans',
      category: 'Jeans',
      image: '/images/mens-jeans-44.jpg',
      price: 300,
      countInStock: 8,
      brand: 'Lee',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality branded jeans',
    },
    {
      _id: '5',
      name: 'Chateux Perfume',
      slug: 'chateux-perfume',
      category: 'Lifestyle',
      image: '/images/perfumes74.jpg',
      price: 290,
      countInStock: 20,
      brand: 'Puma',
      rating: 5,
      numReviews: 9,
      description: 'high Classic perfumes',
    },
    {
      _id: '6',
      name: 'Charllote Perfume',
      slug: 'branded-perfume',
      category: 'Lifestyle',
      image: '/images/perfumes-4.jpg',
      price: 350,
      countInStock: 25,
      brand: 'Ciroc',
      rating: 4.0,
      numReviews: 10,
      description: 'high lasting fragrance perfume',
    },
    {
      _id: '7',
      name: 'Rose Perfume',
      slug: 'rose-perfume',
      category: 'Lifestyle',
      image: '/images/perfumes-14.jpg',
      price: 450,
      countInStock: 4,
      brand: 'Tilt',
      rating: 5,
      numReviews: 10,
      description: 'high quality perfume for top class',
    },
    {
      _id: '8',
      name: 'Lily',
      slug: 'lily-perfume',
      category: 'Lifestyle',
      image: '/images/perfumes-64.jpg',
      price: 400,
      countInStock: 2,
      brand: 'Lily Exotic',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality and lasting fragrance',
    },
  ],
};
export default data;
